#ifndef MESSAGE_H
#define MESSAGE_H

#define GETMACADDR 0
#define SHENJI 1

#if SHENJI
#define CASHNAME "TENANT"
#else
#define CASHNAME "NAME"
#endif

//#define UPDATEFLAG

#define OLDGRANDTOTAL "BEGINNING BALANCE"
#define NEWGRANDTOTAL "ENDING BALANCE"
#define TOTALGROSSSALES "TOTAL GROSS SALES"
#define RECGRANDTOTAL "GRAND TOTAL"
#define RECAMOUNT "AMOUNT"
#define RECNAME "NAME"
#define RECCODE "CODE"
#define RECQUANTITY "QUANTITY"
#define RECDEPARTMENT "DEPARTMENT"
#define TOTALTRADE "TOTAL TRADE"
#define RECEXEMPT "EXEMPT_"
#define ZERO_VAT "ZERO_VAT"
#define ZEORRATEDSALES "ZEOR RATED SALES"
#define VATEXEMPTSALES "VAT EXEMPT SALES"
#define VATEXEMPTAMOUNT "VAT ADJUSTMENT"
#define GROSSSALES "GROSS SALES"
#define TOTALACCUMULATEDSALES "TOTAL ACCUMULATED SALES"

#endif // MESSAGE_H

