#ifndef READEXCELCLASS_GLOBAL_H
#define READEXCELCLASS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(READEXCELCLASS_LIBRARY)
#  define READEXCELCLASSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define READEXCELCLASSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // READEXCELCLASS_GLOBAL_H
